project:
  type: book

book:
  title: "The _Epiverse-TRACE_ blueprints for software development"
  chapters:
    - index.qmd
    - principles.qmd
    - git-branching-merging.qmd
    - code-review.qmd

format:
  html:
    theme: cosmo
    number-sections: false
